import type { IndexerAccount } from '@/types'

/**
 * Runtime configuration loaded from /config.json.
 *
 * This file is generated by the Docker entrypoint from environment variables.
 * It allows pre-configuring API keys and accounts without rebuilding the image.
 *
 * Values are only applied as defaults — if the user already has configuration
 * in localStorage (from the Settings page), those take precedence.
 */
export interface RuntimeConfig {
  theGraphApiKey?: string
  drpcApiKey?: string
  accounts?: IndexerAccount[]
}

/**
 * Fetches runtime configuration from /config.json.
 * Returns an empty object if the file doesn't exist or is invalid
 * (e.g., when running in dev mode without Docker).
 */
export async function loadRuntimeConfig(): Promise<RuntimeConfig> {
  try {
    const resp = await fetch('/config.json')
    if (!resp.ok) return {}
    const data = await resp.json()
    return data as RuntimeConfig
  } catch {
    return {}
  }
}
